services:
    _defaults:
        autoconfigure: true
        autowire: true

    Xx81\Contao\MoreFrontendModulesBundle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Session,Config,Model,Event}'

    # Event-Listener für DataContainer
    Xx81\Contao\MoreFrontendModulesBundle\EventListener\DataContainer\:
        resource: '../src/EventListener/DataContainer/'
        tags: [ 'contao_service_annotation' ]
        arguments:
            - '@request_stack'

    # Modules
    Xx81\Contao\MoreFrontendModulesBundle\Controller\:
        resource: '../src/Controller/'
        tags: [ 'terminal42_service_annotation' ]
        public: true
